# -*- coding: utf-8 -*-
"""HW5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZxY76-FCfnyREoHSEoDMm8APcdSHyTkx
"""

#Вводится строка из нескольких слов, вывести список слов
def string_split(string: str) -> list:
    return string.split()
string_split('Robing Sight Monday  ')

#Натан пьет 0,5 воды в час. Сколько литров выпил округленное до целых
time = 3
def drinking_water(time: int) -> int:
  liters = time // 2
  return liters
drinking_water(time)
#Можно было использовать функцию math.floor

#Функция, которая возвращает список чисел от n до 1, n>0
number = 5
def get_list(number: int) -> list:
  counter = 0
  lst = []
  for value in range(number):
      counter += 1
      value = (number + 1) - counter
      lst.append(value)
  return lst
get_list(number)